#!/bin/bash
read -r -p "请输入一个整数:" num1
read -r -p "请输入一个整数：" num2
read -p "请输入一个整数：" -r num3
# read -r 禁用反斜杠换行
tmp=0
if [ $num1 -gt $num2 ];then
    tmp=$num1
    num1=$num2
    num2=$tmp
fi

if [ $num1 -gt $num3 ];then
    tmp=$num1
    num1=$num3
    num3=$tmp
fi

if [ $num2 -gt $num3 ];then
    tmp=$num2
    num2=$num3
    num3=$tmp
fi

echo "排序后的数据为：$num1, $num2, $num3"


