#!/bin/bash

#LDMP Linux Nginx MySQL PHP
yum -y install httpd
yum -y install mariadb mariadb-devel mariadb-server
yum -y install php php-MySQL

systemctl start httpd
systemctl start mariadb
systemctl enable httpdb
systemctl enable mariadb

