#!/bin/bash
#RANDOM是系统自带的变量，0-32767. 取余算法变成1-100

#num=$[RANDOM%100+1]
num=$((RANDOM%100+1))


#使用read提示用户猜数字

while :
do
    read -p "计算机生成了一个1-100的随机数，你猜：" cai
    if [ $cai -eq $num ];then
    echo "恭喜 猜对了" 
    exit
    elif [ $cai -gt $num ];then
        echo "Oops,猜大了"
    else
        echo "Oops,猜小了"
    fi
done